package oms.localization

object Strings {

    val uk = mapOf(
        "construction_type" to "Тип будівництва",
        "construction_reconstruction" to "Реконструкція",
        "construction_capital_repair" to "Капітальний ремонт",
        "construction_new_construction" to "Нове будівництво",
        "no_recent_activity" to "Нещодавніх дій ще немає.",
        "activity_project_created" to "Створено проєкт або субпроєкт",
        "activity_project_deleted" to "Видалено проєкт або субпроєкт",
        "activity_inspection_imported" to "Імпортовано інспекційний звіт",
        "activity_financial_created" to "Додано фінансовий запис",
        "activity_financial_imported" to "Імпортовано фінансові записи",
        "subproject" to "Субпроєкт",
        "subproject_part" to "Частина субпроєкту",
        "choose_date" to "Вибрати дату",
        "password_requirements" to "Пароль має містити щонайменше 8 символів.",
        "projects_subprojects" to "Проєкти / субпроєкти",
        "subprojects" to "Субпроєкти",
        "no_subprojects" to "Субпроєкти ще не додані.",
        "projects_by_start_month" to "Проєкти за місяцем початку робіт",
        "no_projects_with_start_date" to "Немає проєктів із вказаною датою початку.",
        "monthly_project_payments" to "Виплати за проєктами по місяцях",
        "no_payments_yet" to "Виплат ще немає.",
        "dashboard" to "Головна панель",
        "projects" to "Проєкти",
        "map" to "Карта",
        "inspection_reports" to "Інспекційні звіти",
        "login" to "Увійти",
        "project" to "Проєкт",
        "region" to "Регіон",
        "status" to "Статус",
        "actions" to "Дії",
        "action" to "Дія",

        "financial_monitoring" to "Фінансовий моніторинг",
        "financial_access_restricted" to "Фінансові дані обмежені. Зверніться до свого менеджера проєкту.",
        "access_restricted" to "Доступ обмежено",
        "import_xls" to "Імпортувати XLS",
        "export_to_excel" to "Експортувати в Excel",
        "add_record" to "Додати запис",
        "monthly_payments" to "Щомісячні платежі",
        "record_type" to "Тип запису",
        "record_type_invoice" to "Рахунок",
        "record_type_act" to "Акт",
        "record_type_payment" to "Платіж",
        "record_type_advance" to "Аванс",
        "all_dates" to "Усі дати",
        "documents" to "Документи",
        "logout" to "Вийти",
        "user" to "Користувач",
        "admin" to "Адміністратор",

        "projects_map" to "Карта проєктів",
        "map_controls" to "Елементи керування картою",
        "map_projects_info" to "На карті відображаються всі проєкти з локального репозиторію.",
        "map_marker_info" to "Колір маркера відповідає статусу проєкту.",
        "markers_count" to "Кількість маркерів:",
        "active" to "Активний",
        "planning" to "Планування",
        "completed" to "Завершено",

        "projects_title" to "Проєкти",
        "search_project" to "Пошук проєкту",
        "search" to "Пошук",
        "sort" to "Сортування",
        "id" to "ID",
        "name" to "Назва",
        "open" to "Відкрити",

        "documents_title" to "Документи",
        "upload_document" to "Завантажити документ",
        "uploaded_by" to "Завантажив",
        "type" to "Тип",
        "newest_first" to "Спочатку новіші",
        "oldest_first" to "Спочатку старіші",
        "no_documents" to "Документи ще не додані. Натисніть «Завантажити документ», щоб додати перший.",
        "icon" to "Іконка",
        "filename" to "Ім'я файлу",
        "date" to "Дата",
        "size" to "Розмір",

        "contract" to "Контракт",
        "design" to "Проєкт",
        "estimate" to "Кошторис",
        "financial_doc" to "Фінансовий документ",
        "photo" to "Фото",

        "welcome_back" to "Ласкаво просимо",
        "please_sign_in" to "Будь ласка, увійдіть, щоб продовжити",
        "email" to "Електронна пошта",
        "password" to "Пароль",
        "remember_me" to "Запам'ятати мене",
        "forgot_password" to "Забули пароль?",
        "sign_in" to "Увійти",
        "toggle_password" to "Показати/сховати пароль",
        "email_required" to "Потрібно вказати email",
        "password_required" to "Потрібно вказати пароль",
        "invalid_credentials" to "Невірні облікові дані",

        "login_hero_title" to "Система онлайн-моніторингу.",
        "login_hero_subtitle" to "Єдина система для відстеження проєктів, інспекцій і фінансового контролю.",
        "feature_realtime_monitoring" to "Моніторинг проєктів у реальному часі",
        "feature_inspection_reports" to "Інтегровані інспекційні звіти",
        "feature_financial_tools" to "Інструменти фінансової прозорості",

        "reports_title" to "Інспекційні звіти",
        "report_id" to "ID звіту",
        "report_type" to "Тип",
        "inspector" to "Інспектор",
        "view" to "Деталі",
        "edit" to "Редагувати",
        "new_inspection" to "Створити інспекцію",
        "draft" to "Чернетка",
        "pending_review" to "Очікує перевірки",
        "site_visit" to "Виїзд на об'єкт",
        "safety_check" to "Перевірка безпеки",
        "progress_audit" to "Аудит прогресу",
        "quality_review" to "Перевірка якості",

        "projects_by_region" to "Проєкти за регіонами",
        "reports" to "Звіти",
        "issues" to "Проблеми",
        "recent_activity" to "Нещодавні дії",
        "project_updated" to "Проєкт оновлено",
        "inspection_completed" to "Інспекцію завершено",
        "new_report_uploaded" to "Завантажено новий звіт",
        "time_2_hours_ago" to "2 години тому",
        "time_5_hours_ago" to "5 годин тому",
        "time_yesterday" to "Вчора",
        "reports_by_month" to "Звіти за місяцями",
        "chart_placeholder" to "Заглушка графіка",
        "total_budget" to "Загальний бюджет",
        "in_progress" to "У процесі",
        "delayed" to "Затримано",

        "all" to "Усі",
        "budget_summary" to "Зведення бюджету",
        "spent_remaining" to "% витрачено / % залишилось",
        "spent" to "Витрачено",
        "remaining" to "Залишилось",

        "invoice_no" to "Рахунок №",
        "payment_date" to "Дата оплати",
        "amount" to "Сума",
        "currency" to "Валюта",
        "milestone" to "Етап",
        "planned" to "Плановий",
        "unplanned" to "Позаплановий",
        "final" to "Підсумковий",

        "edit_inspection" to "Редагувати інспекцію",
        "create_inspection" to "Створити інспекцію",
        "rejected" to "Відхилено",
        "cannot_be_future_date" to "Не може бути датою в майбутньому",
        "gps_coordinates" to "GPS-координати",
        "optional_on_web_accuracy_warning" to "Необов’язково для веб. Попередження про точність, якщо > 50 м.",
        "comments" to "Коментарі",
        "photos" to "Фото",
        "drag_and_drop_zone" to "Зона перетягування / завантаження з камери",
        "no_photos_uploaded_yet" to "Фото ще не завантажено.",
        "photo_thumbnails_go_here" to "Тут будуть мініатюри фото",
        "save_draft" to "Зберегти чернетку",
        "submit_report" to "Надіслати звіт",
        "inspector_label" to "Інспектор",
        "date_label" to "Дата",

        "address" to "Адреса",
        "sector" to "Сектор",
        "budget_planned" to "Плановий бюджет",
        "amount_spent" to "Витрачено",
        "budget_remaining" to "Залишилось",
        "general_info" to "Загальна інформація",
        "inspection_reports_tab" to "Інспекційні звіти",
        "financials" to "Фінанси",
        "documents" to "Документи",
        "incidents" to "Інциденти",
        "coming_next" to "Найближчим часом",
        "project_documents" to "Документи проєкту",
        "sir_source_files" to "Вихідні файли SIR",
        "upload_document" to "Завантажити документ",
        "select_project" to "Оберіть проєкт",
        "select_subproject" to "Оберіть субпроєкт",
        "select_subproject_part" to "Оберіть частину субпроєкту",
        "choose_file" to "Вибрати файл",
        "cancel" to "Скасувати",
        "save" to "Зберегти",
        "close" to "Закрити",
        "delete" to "Видалити",
        "open_document" to "Відкрити документ",
        "no_project_documents" to "Документів проєкту не знайдено.",
        "no_reports" to "Інспекційних звітів не знайдено.",
        "inspection_report" to "Інспекційний звіт",
        "financial_records" to "Фінансові записи",
        "completed_works_by_acts" to "Сума виконаних робіт за актами",
        "only_completed_works" to "Враховуються лише виконані роботи, підтверджені актами.",
        "no_acts" to "Актів не знайдено.",
        "act_documents" to "Документи-акти",
        "uploaded_by" to "Завантажив",
        "file_name" to "Ім'я файлу",
        "subproject" to "Субпроєкт",
        "other" to "Інше",
        "draft_status" to "Чернетка",
        "pending_review_status" to "Очікує перевірки",
        "completed_status" to "Завершено",
        "role_admin" to "Адміністратор",
        "role_project_manager" to "Менеджер проєкту",
        "role_inspector" to "Інспектор",
        "general_info_tab" to "Загальна інформація",
        "incidents_hse" to "Інциденти (ОПіЗ)",
        "upload_photo" to "Завантажити фото",
        "findings" to "Зауваження",
        "move_report" to "Перемістити звіт",
        "delete_report" to "Видалити звіт",
        "inspection_findings" to "Зауваження інспекції",
        "no_findings" to "Зауважень ще немає.",
        "add_finding" to "Додати зауваження",
        "edit_finding" to "Редагувати зауваження",
        "category" to "Категорія",
        "description" to "Опис",
        "recommendation" to "Рекомендація",
        "resolved" to "Вирішено",
        "reopen" to "Відкрити знову",
        "resolve" to "Вирішити",
        "select_target_project" to "Оберіть цільовий проєкт",
        "no_other_project" to "Немає іншого проєкту для вибору.",
        "move" to "Перемістити",
        "date" to "Дата",
        "report_project" to "Звіт / проєкт",
        "no_sir_reports_uploaded" to "Звіти ще не завантажено",
        "hse_upload_report_hint" to "Після завантаження SIR тут з’являться спостереження з розділу OBSERVANCES ON HEALTH & SAFETY.",
        "no_hse_observations" to "У завантажених звітах немає даних з ОПіЗ",
        "hse_section_hint" to "Переконайтеся, що вихідний SIR містить розділ OBSERVANCES ON HEALTH & SAFETY.",
        "hse_observations_title" to "Спостереження з SIR: OBSERVANCES ON HEALTH & SAFETY",
        "inspection_date_prefix" to "Інспекція від",
        "answer" to "Відповідь",
        "review_inspection_report" to "Перевірка інспекційного звіту",
        "revision_reason" to "Причина повернення на доопрацювання",
        "return_for_revision" to "Повернути на доопрацювання",
        "approve" to "Схвалити",
        "no_imported_sir_files" to "Імпортованих файлів SIR не знайдено.",
        "add_inspection_photos" to "Додати фото — перетягніть або виберіть файли",
        "no_photos_selected" to "Фото ще не вибрано.",
        "photos_selected" to "Вибрано фото: {count} з 30. Відкрийте область ще раз, щоб переглянути або видалити їх.",
        "photo_upload_requirements" to "Лише JPEG або PNG, до 10 МБ кожен.",
        "procurement_title" to "Закупівлі",
        "procurement_subtitle" to "Контракти на будівельні роботи за субпроєктами",
        "procurement_load_error" to "Не вдалося завантажити дані закупівель.",
        "proc_number" to "№",
        "proc_batch_number" to "Номер пулу",
        "proc_oblast_name" to "Назва області",
        "proc_oblast_id" to "Ідентифікатор області",
        "proc_subproject_id" to "Ідентифікатор субпроєкту",
        "proc_subproject_lot_id" to "Ідентифікатор лоту субпроєкту",
        "procurement_status" to "Статус закупівлі будробіт",
        "proc_tender_id" to "Ідентифікатор тендеру",
        "proc_prozorro_tender_id" to "Ідентифікатор тендеру на PROZORRO",
        "proc_contractor_name_uk" to "Назва підрядника (укр.)",
        "proc_contractor_name_en" to "Назва підрядника (англ.)",
        "proc_contractor_edrpou" to "Код ЄДРПОУ підрядника",
        "proc_contract_date" to "Дата контракту",
        "proc_contract_end_date" to "Дата завершення контракту",
        "proc_contract_duration" to "Тривалість контракту (робіт), місяці",
        "proc_contract_amount_uah" to "Сума договору на будівництво з ПДВ, грн",
        "proc_contract_amount_eur" to "Сума договору з ПДВ, EUR",
        "proc_financing_difference" to "Різниця між фінансуванням і сумою договору, %",
        "import_export_xlsx" to "Імпорт / експорт XLSX",
        "financial_transfer_title" to "Імпорт або експорт фінансових записів",
        "financial_import_hint" to "Імпорт приймає XLSX-файл, експортований системою для вибраного проєкту.",
        "add_financial_record" to "Додати фінансовий запис",
        "edit_financial_record" to "Редагувати фінансовий запис",
        "reference_number" to "Реєстраційний номер",
        "amount_uah" to "Сума, грн",
        "tranche" to "Транш",
        "city" to "Місто",
        "budget" to "Бюджет",
        "start_date" to "Дата початку",
        "contractor" to "Підрядник",
        "construction_contract" to "Будівельний контракт",
        "acts_of_completed_works" to "Акти виконаних робіт",
        "financial_completion" to "Фінансове виконання",
        "delete_project" to "Видалити проєкт",
        "delete_document_error" to "Не вдалося видалити документ.",
        "source_file" to "Вихідний файл SIR",
        "open_source_file" to "Відкрити вихідний файл SIR",
        "delete_source_file" to "Видалити вихідний файл SIR",
        "delete_source_file_error" to "Не вдалося видалити вихідний документ.",
        "edit_financial_record_tooltip" to "Редагувати фінансовий запис",
        "delete_financial_record_tooltip" to "Видалити фінансовий запис",
        "user_status_active" to "Активний",
        "user_status_pending" to "Очікує",
        "user_status_disabled" to "Вимкнений",
        "severity_low" to "Низька",
        "severity_medium" to "Середня",
        "severity_high" to "Висока",
        "severity_critical" to "Критична"
    )

    val en = mapOf(
        "construction_reconstruction" to "Reconstruction",
        "construction_capital_repair" to "Capital repair",
        "construction_new_construction" to "New construction",
        "no_recent_activity" to "No recent activity yet.",
        "activity_project_created" to "Project or subproject created",
        "activity_project_deleted" to "Project or subproject deleted",
        "activity_inspection_imported" to "Inspection report imported",
        "activity_financial_created" to "Financial record added",
        "activity_financial_imported" to "Financial records imported",
        "subproject" to "Subproject",
        "subproject_part" to "Subproject part",
        "choose_date" to "Choose date",
        "password_requirements" to "Password must contain at least 8 characters.",
        "projects_subprojects" to "Projects / subprojects",
        "subprojects" to "Subprojects",
        "no_subprojects" to "No subprojects yet.",
        "projects_by_start_month" to "Projects by work start month",
        "no_projects_with_start_date" to "No projects have a start date yet.",
        "monthly_project_payments" to "Monthly project payments",
        "no_payments_yet" to "No payments yet.",
        "dashboard" to "Dashboard",
        "projects" to "Projects",
        "map" to "Map",
        "inspection_reports" to "Inspection Reports",
        "login" to "Login",

        "financial_monitoring" to "Financial Monitoring",
        "financial_access_restricted" to "Financial data is restricted. Contact your Project Manager.",
        "access_restricted" to "Access restricted",
        "import_xls" to "Import XLS",
        "export_to_excel" to "Export to Excel",
        "add_record" to "Add Record",
        "monthly_payments" to "Monthly Payments",
        "record_type" to "Record Type",
        "record_type_invoice" to "Invoice",
        "record_type_act" to "Act",
        "record_type_payment" to "Payment",
        "record_type_advance" to "Advance",
        "all_dates" to "All dates",
        "documents" to "Documents",
        "logout" to "Logout",
        "user" to "User",
        "admin" to "Admin",

        "projects_map" to "Projects Map",
        "map_controls" to "Map Controls",
        "map_projects_info" to "The map shows all projects from the local repository.",
        "map_marker_info" to "Marker color matches the project status.",
        "markers_count" to "Markers count:",
        "region" to "Region",
        "status" to "Status",
        "active" to "Active",
        "planning" to "Planning",
        "completed" to "Completed",

        "projects_title" to "Projects",
        "search_project" to "Search project",
        "search" to "Search",
        "project" to "Project",
        "sort" to "Sort",
        "id" to "ID",
        "name" to "Name",
        "open" to "Open",

        "documents_title" to "Documents",
        "upload_document" to "Upload Document",
        "uploaded_by" to "Uploaded by",
        "type" to "Type",
        "newest_first" to "Newest first",
        "oldest_first" to "Oldest first",
        "no_documents" to "No documents uploaded yet. Click Upload Document to add the first one.",
        "icon" to "Icon",
        "filename" to "Filename",
        "date" to "Date",
        "size" to "Size",
        "actions" to "Actions",

        "contract" to "Contract",
        "design" to "Design",
        "estimate" to "Estimate",
        "financial_doc" to "Financial Doc",
        "photo" to "Photo",

        "welcome_back" to "Welcome back",
        "please_sign_in" to "Please sign in to continue",
        "email" to "Email",
        "password" to "Password",
        "remember_me" to "Remember me",
        "forgot_password" to "Forgot password?",
        "sign_in" to "Sign in",
        "toggle_password" to "Toggle password visibility",
        "email_required" to "Email is required",
        "password_required" to "Password is required",
        "invalid_credentials" to "Invalid credentials",

        "login_hero_title" to "Online Monitoring System",
        "login_hero_subtitle" to "A unified system for project tracking, inspections, and financial oversight.",
        "feature_realtime_monitoring" to "Real-time project monitoring",
        "feature_inspection_reports" to "Integrated inspection reports",
        "feature_financial_tools" to "Financial transparency tools",

        "reports_title" to "Inspection Reports",
        "report_id" to "Report ID",
        "report_type" to "Type",
        "inspector" to "Inspector",
        "view" to "View",
        "edit" to "Edit",
        "new_inspection" to "New Inspection",
        "draft" to "Draft",
        "pending_review" to "Pending Review",
        "site_visit" to "Site Visit",
        "safety_check" to "Safety Check",
        "progress_audit" to "Progress Audit",
        "quality_review" to "Quality Review",

        "projects_by_region" to "Projects by Region",
        "reports" to "Reports",
        "issues" to "Issues",
        "recent_activity" to "Recent Activity",
        "project_updated" to "Project updated",
        "inspection_completed" to "Inspection completed",
        "new_report_uploaded" to "New report uploaded",
        "time_2_hours_ago" to "2 hours ago",
        "time_5_hours_ago" to "5 hours ago",
        "time_yesterday" to "Yesterday",
        "reports_by_month" to "Reports by Month",
        "chart_placeholder" to "Chart placeholder",
        "total_budget" to "Total Budget",
        "in_progress" to "In Progress",
        "delayed" to "Delayed",

        "all" to "All",
        "budget_summary" to "Budget summary",
        "spent_remaining" to "% spent / % remaining",
        "spent" to "Spent",
        "remaining" to "Remaining",

        "invoice_no" to "Invoice #",
        "payment_date" to "Payment Date",
        "amount" to "Amount",
        "currency" to "Currency",
        "milestone" to "Milestone",
        "planned" to "Planned",
        "unplanned" to "Unplanned",
        "final" to "Final",

        "edit_inspection" to "Edit Inspection",
        "create_inspection" to "Create Inspection",
        "rejected" to "Rejected",
        "cannot_be_future_date" to "Cannot be a future date",
        "gps_coordinates" to "GPS coordinates",
        "optional_on_web_accuracy_warning" to "Optional on web. Accuracy warning if > 50m.",
        "comments" to "Comments",
        "photos" to "Photos",
        "drag_and_drop_zone" to "Drag-and-drop zone / camera upload",
        "no_photos_uploaded_yet" to "No photos uploaded yet.",
        "photo_thumbnails_go_here" to "Photo thumbnails go here",
        "save_draft" to "Save Draft",
        "submit_report" to "Submit Report",
        "inspector_label" to "Inspector",
        "date_label" to "Date",

        "address" to "Address",
        "sector" to "Sector",
        "construction_type" to "Construction type",
        "budget_planned" to "Budget Planned",
        "amount_spent" to "Amount Spent",
        "budget_remaining" to "Budget Remaining",
        "general_info" to "General Info",
        "inspection_reports_tab" to "Inspection Reports",
        "financials" to "Financials",
        "documents_tab" to "Documents",
        "incidents" to "Incidents",
        "coming_next" to "Coming next",
        "project_documents" to "Project documents",
        "sir_source_files" to "SIR source files",
        "select_project" to "Select project",
        "select_subproject" to "Select subproject",
        "select_subproject_part" to "Select subproject part",
        "choose_file" to "Choose file",
        "cancel" to "Cancel",
        "save" to "Save",
        "close" to "Close",
        "delete" to "Delete",
        "open_document" to "Open document",
        "no_project_documents" to "No project documents found.",
        "no_reports" to "No inspection reports found.",
        "inspection_report" to "Inspection report",
        "financial_records" to "Financial records",
        "completed_works_by_acts" to "Sum of completed works by acts",
        "only_completed_works" to "Only completed works confirmed by acts are included.",
        "no_acts" to "No acts found.",
        "act_documents" to "Act documents",
        "file_name" to "File name",
        "subproject" to "Subproject",
        "other" to "Other",
        "draft_status" to "Draft",
        "pending_review_status" to "Pending review",
        "completed_status" to "Completed",
        "role_admin" to "Administrator",
        "role_project_manager" to "Project Manager",
        "role_inspector" to "Inspector",
        "general_info_tab" to "General Info",
        "incidents_hse" to "Incidents (HSE)",
        "upload_photo" to "Upload photo",
        "findings" to "Findings",
        "move_report" to "Move report",
        "delete_report" to "Delete report",
        "inspection_findings" to "Inspection findings",
        "no_findings" to "No findings yet.",
        "add_finding" to "Add finding",
        "edit_finding" to "Edit finding",
        "category" to "Category",
        "description" to "Description",
        "recommendation" to "Recommendation",
        "resolved" to "Resolved",
        "reopen" to "Reopen",
        "resolve" to "Resolve",
        "select_target_project" to "Select target project",
        "no_other_project" to "There is no other project to select.",
        "move" to "Move",
        "report_project" to "Report / project",
        "no_sir_reports_uploaded" to "No inspection reports have been uploaded yet",
        "hse_upload_report_hint" to "Observations from the OBSERVANCES ON HEALTH & SAFETY section will appear here after a SIR is uploaded.",
        "no_hse_observations" to "No HSE observations were found in the uploaded reports",
        "hse_section_hint" to "Make sure the original SIR contains an OBSERVANCES ON HEALTH & SAFETY section.",
        "hse_observations_title" to "SIR observations: OBSERVANCES ON HEALTH & SAFETY",
        "inspection_date_prefix" to "Inspection on",
        "answer" to "Answer",
        "review_inspection_report" to "Review inspection report",
        "revision_reason" to "Reason for returning for revision",
        "return_for_revision" to "Return for revision",
        "approve" to "Approve",
        "no_imported_sir_files" to "No imported SIR files found.",
        "add_inspection_photos" to "Add photos — drag and drop or select files",
        "no_photos_selected" to "No photos selected yet.",
        "photos_selected" to "{count} of 30 photos selected. Open the area again to preview or remove them.",
        "photo_upload_requirements" to "JPEG or PNG only, up to 10 MB each.",
        "procurement_title" to "Procurement",
        "procurement_subtitle" to "Construction works contracts by subproject",
        "procurement_load_error" to "Could not load procurement data.",
        "proc_number" to "No.",
        "proc_batch_number" to "Pool number",
        "proc_oblast_name" to "Oblast name",
        "proc_oblast_id" to "Oblast identifier",
        "proc_subproject_id" to "Subproject identifier",
        "proc_subproject_lot_id" to "Subproject lot identifier",
        "procurement_status" to "Construction procurement status",
        "proc_tender_id" to "Tender identifier",
        "proc_prozorro_tender_id" to "PROZORRO tender identifier",
        "proc_contractor_name_uk" to "Contractor name (Ukrainian)",
        "proc_contractor_name_en" to "Contractor name (English)",
        "proc_contractor_edrpou" to "Contractor EDRPOU code",
        "proc_contract_date" to "Contract date",
        "proc_contract_end_date" to "Contract end date",
        "proc_contract_duration" to "Contract works duration, months",
        "proc_contract_amount_uah" to "Construction contract amount incl. VAT, UAH",
        "proc_contract_amount_eur" to "Contract amount incl. VAT, EUR",
        "proc_financing_difference" to "Difference between financing and contract amount, %",
        "import_export_xlsx" to "Import / export XLSX",
        "financial_transfer_title" to "Import or export financial records",
        "financial_import_hint" to "Import accepts an XLSX file exported by the system for the selected project.",
        "add_financial_record" to "Add financial record",
        "edit_financial_record" to "Edit financial record",
        "reference_number" to "Reference number",
        "amount_uah" to "Amount, UAH",
        "tranche" to "Tranche",
        "city" to "City",
        "budget" to "Budget",
        "start_date" to "Start date",
        "contractor" to "Contractor",
        "construction_contract" to "Construction contract",
        "acts_of_completed_works" to "Acts of completed works",
        "financial_completion" to "Financial completion",
        "delete_project" to "Delete project",
        "delete_document_error" to "Could not delete document.",
        "source_file" to "SIR source file",
        "open_source_file" to "Open SIR source file",
        "delete_source_file" to "Delete SIR source file",
        "delete_source_file_error" to "Could not delete source document.",
        "edit_financial_record_tooltip" to "Edit financial record",
        "delete_financial_record_tooltip" to "Delete financial record",
        "user_status_active" to "Active",
        "user_status_pending" to "Pending",
        "user_status_disabled" to "Disabled",
        "severity_low" to "Low",
        "severity_medium" to "Medium",
        "severity_high" to "High",
        "severity_critical" to "Critical"
    )
}
