package oms.localization

object Strings {

    val uk = mapOf(
        "construction_type" to "Тип будівництва",
        "construction_reconstruction" to "Реконструкція",
        "construction_capital_repair" to "Капітальний ремонт",
        "construction_new_construction" to "Нове будівництво",
        "no_recent_activity" to "Нещодавніх дій ще немає.",
        "activity_project_created" to "Створено проєкт або субпроєкт",
        "activity_project_deleted" to "Видалено проєкт або субпроєкт",
        "activity_inspection_imported" to "Імпортовано інспекційний звіт",
        "activity_inspection_manual_created" to "Створено інспекційний звіт вручну",
        "activity_financial_created" to "Додано фінансовий запис",
        "activity_financial_imported" to "Імпортовано фінансові записи",
        "activity_financial_moved" to "Перенесено фінансовий запис",
        "activity_projects_bulk_status_updated" to "Оновлено статуси проєктів",
        "activity_projects_bulk_reassigned" to "Змінено відповідальних за проєкти",
        "activity_user_created" to "Створено користувача",
        "activity_user_updated" to "Оновлено дані користувача",
        "activity_user_status_changed" to "Змінено статус користувача",
        "activity_user_role_changed" to "Змінено роль користувача",
        "activity_user_password_reset" to "Скинуто пароль користувача",
        "activity_user_deleted" to "Видалено користувача",
        "activity_user_activated" to "Активовано обліковий запис",
        "subproject" to "Субпроєкт",
        "subproject_part" to "Частина субпроєкту",
        "choose_date" to "Вибрати дату",
        "password_requirements" to "Пароль має містити щонайменше 8 символів.",
        "projects_subprojects" to "Проєкти / субпроєкти",
        "subprojects" to "Субпроєкти",
        "no_subprojects" to "Субпроєкти ще не додані.",
        "projects_by_start_month" to "Проєкти за місяцем початку робіт",
        "subprojects_count" to "Кількість субпроєктів: {count}",
        "start_month_axis_label" to "Місяць початку робіт",
        "monthly_act_payments" to "Сума по погодженим актам виконаних робіт",
        "monthly_act_payments_hint" to "Суми актів згруповано за датою оплати (або датою акта).",
        "no_projects_with_start_date" to "Немає проєктів із вказаною датою початку.",
        "monthly_project_payments" to "Виплати за проєктами по місяцях",
        "no_payments_yet" to "Виплат ще немає.",
        "dashboard" to "Головна панель",
        "projects" to "Проєкти",
        "map" to "Карта",
        "inspection_reports" to "Інспекційні звіти",
        "login" to "Увійти",
        "project" to "Проєкт",
        "region" to "Область",
        "status" to "Статус",
        "actions" to "Дії",
        "action" to "Дія",

        "financial_monitoring" to "Фінансовий моніторинг",
        "financial_access_restricted" to "Фінансові дані обмежені. Зверніться до свого менеджера проєкту.",
        "access_restricted" to "Доступ обмежено",
        "import_xls" to "Імпортувати XLS",
        "export_to_excel" to "Експортувати в Excel",
        "add_record" to "Додати запис",
        "monthly_payments" to "Щомісячні платежі",
        "record_type" to "Тип запису",
        "record_type_invoice" to "Рахунок",
        "record_type_act" to "Акт",
        "record_type_payment" to "Платіж",
        "record_type_advance" to "Аванс",
        "all_dates" to "Усі дати",
        "documents" to "Документи",
        "logout" to "Вийти",
        "user" to "Користувач",
        "admin" to "Адміністратор",

        "projects_map" to "Карта проєктів",
        "map_controls" to "Елементи керування картою",
        "map_projects_info" to "На карті відображаються проєкти, доступні поточному користувачу.",
        "map_marker_info" to "Колір маркера відповідає статусу проєкту.",
        "markers_count" to "Кількість маркерів:",
        "active" to "Активний",
        "planning" to "Планування",
        "completed" to "Завершено",

        "projects_title" to "Проєкти",
        "search_project" to "Пошук проєкту",
        "filter_label" to "Фільтр: {name}",
        "filters" to "Фільтри",
        "geocode_address" to "Розрахувати за адресою",
        "geocode_address_loading" to "Розрахунок координат…",
        "geocode_address_required" to "Вкажіть адресу, місто або область для розрахунку координат.",
        "geocode_address_not_found" to "Не вдалося визначити координати за вказаною адресою.",
        "geocode_attribution" to "Геодані © OpenStreetMap contributors",
        "map_scope" to "Показати на карті",
        "map_subprojects" to "Субпроєкти",
        "map_subproject_parts" to "Частини субпроєктів",
        "expand" to "Розгорнути",
        "collapse" to "Згорнути",
        "sector_education" to "Освіта",
        "sector_healthcare" to "Охорона здоров’я",
        "sector_shelter" to "Укриття",
        "search" to "Пошук",
        "sort" to "Сортування",
        "id" to "ID",
        "name" to "Назва",
        "open" to "Відкрити",

        "documents_title" to "Документи",
        "upload_document" to "Завантажити документ",
        "uploaded_by" to "Завантажив",
        "type" to "Тип",
        "newest_first" to "Спочатку новіші",
        "oldest_first" to "Спочатку старіші",
        "no_documents" to "Документи ще не додані. Натисніть «Завантажити документ», щоб додати перший.",
        "icon" to "Іконка",
        "filename" to "Ім'я файлу",
        "date" to "Дата",
        "size" to "Розмір",

        "contract" to "Контракт",
        "design" to "Проєкт",
        "estimate" to "Кошторис",
        "financial_doc" to "Фінансовий документ",
        "photo" to "Фото",

        "welcome_back" to "Ласкаво просимо",
        "please_sign_in" to "Будь ласка, увійдіть, щоб продовжити",
        "email" to "Електронна пошта",
        "password" to "Пароль",
        "remember_me" to "Запам'ятати мене",
        "forgot_password" to "Забули пароль?",
        "continue_as_guest" to "Продовжити як гість",
        "guest_access_error" to "Не вдалося відкрити гостьовий доступ.",
        "password_reset_title" to "Відновлення пароля",
        "password_reset_hint" to "Вкажіть логін або email. Ми надішлемо посилання для встановлення нового пароля.",
        "password_reset_send" to "Надіслати посилання",
        "password_reset_sent" to "Якщо обліковий запис існує, посилання для відновлення надіслано.",
        "password_reset_failed" to "Не вдалося надіслати посилання для відновлення.",
        "sign_in" to "Увійти",
        "toggle_password" to "Показати/сховати пароль",
        "email_required" to "Потрібно вказати email",
        "password_required" to "Потрібно вказати пароль",
        "invalid_credentials" to "Невірні облікові дані",

        "login_hero_title" to "Система онлайн-моніторингу.",
        "login_hero_subtitle" to "Єдина система для відстеження проєктів, інспекцій і фінансового контролю.",
        "feature_realtime_monitoring" to "Моніторинг проєктів у реальному часі",
        "feature_inspection_reports" to "Інтегровані інспекційні звіти",
        "feature_financial_tools" to "Інструменти фінансової прозорості",

        "reports_title" to "Інспекційні звіти",
        "report_id" to "ID звіту",
        "report_type" to "Тип",
        "inspector" to "Інспектор",
        "view" to "Деталі",
        "edit" to "Редагувати",
        "new_inspection" to "Створити інспекцію",
        "draft" to "Чернетка",
        "pending_review" to "Очікує перевірки",
        "site_visit" to "Виїзд на об'єкт",
        "safety_check" to "Перевірка безпеки",
        "progress_audit" to "Аудит прогресу",
        "quality_review" to "Перевірка якості",

        "projects_by_region" to "Проєкти за регіонами",
        "reports" to "Звіти",
        "issues" to "Проблеми",
        "recent_activity" to "Нещодавні дії",
        "project_updated" to "Проєкт оновлено",
        "inspection_completed" to "Інспекцію завершено",
        "new_report_uploaded" to "Завантажено новий звіт",
        "time_2_hours_ago" to "2 години тому",
        "time_5_hours_ago" to "5 годин тому",
        "time_yesterday" to "Вчора",
        "reports_by_month" to "Звіти за місяцями",
        "chart_placeholder" to "Заглушка графіка",
        "total_budget" to "Загальний бюджет",
        "active_projects" to "Активні проєкти",
        "completed_this_month" to "Завершено цього місяця",
        "pending_inspections" to "Інспекції на перевірці",
        "in_progress" to "У процесі",
        "delayed" to "Затримано",

        "all" to "Усі",
        "budget_summary" to "Зведення бюджету",
        "spent_remaining" to "% витрачено / % залишилось",
        "spent" to "Витрачено",
        "remaining" to "Залишилось",

        "invoice_no" to "Рахунок №",
        "payment_date" to "Дата оплати",
        "amount" to "Сума",
        "currency" to "Валюта",
        "currency_eur" to "Євро (EUR)",
        "currency_uah" to "Гривня (UAH)",
        "milestone" to "Етап",
        "planned" to "Плановий",
        "unplanned" to "Позаплановий",
        "final" to "Підсумковий",

        "edit_inspection" to "Редагувати інспекцію",
        "create_inspection" to "Створити інспекцію",
        "rejected" to "Відхилено",
        "cannot_be_future_date" to "Не може бути датою в майбутньому",
        "gps_coordinates" to "GPS-координати",
        "optional_on_web_accuracy_warning" to "Необов’язково для веб. Попередження про точність, якщо > 50 м.",
        "comments" to "Коментарі",
        "photos" to "Фото",
        "drag_and_drop_zone" to "Зона перетягування / завантаження з камери",
        "no_photos_uploaded_yet" to "Фото ще не завантажено.",
        "photo_thumbnails_go_here" to "Тут будуть мініатюри фото",
        "save_draft" to "Зберегти чернетку",
        "submit_report" to "Надіслати звіт",
        "inspector_label" to "Інспектор",
        "date_label" to "Дата",

        "address" to "Адреса",
        "sector" to "Сектор",
        "budget_planned" to "Плановий бюджет",
        "amount_spent" to "Витрачено",
        "budget_remaining" to "Залишилось",
        "general_info" to "Загальна інформація",
        "inspection_reports_tab" to "Інспекційні звіти",
        "financials" to "Фінанси",
        "documents" to "Документи",
        "incidents" to "Інциденти",
        "coming_next" to "Найближчим часом",
        "project_documents" to "Документи проєкту",
        "sir_source_files" to "Вихідні файли SIR",
        "upload_document" to "Завантажити документ",
        "select_project" to "Оберіть проєкт",
        "select_subproject" to "Оберіть субпроєкт",
        "select_subproject_part" to "Оберіть частину субпроєкту",
        "choose_file" to "Вибрати файл",
        "cancel" to "Скасувати",
        "save" to "Зберегти",
        "close" to "Закрити",
        "delete" to "Видалити",
        "open_document" to "Відкрити документ",
        "no_project_documents" to "Документів проєкту не знайдено.",
        "no_reports" to "Інспекційних звітів не знайдено.",
        "inspection_report" to "Інспекційний звіт",
        "financial_records" to "Фінансові записи",
        "completed_works_by_acts" to "Сума виконаних робіт за актами",
        "only_completed_works" to "Враховуються лише виконані роботи, підтверджені актами.",
        "no_acts" to "Актів не знайдено.",
        "act_documents" to "Документи-акти",
        "uploaded_by" to "Завантажив",
        "file_name" to "Ім'я файлу",
        "subproject" to "Субпроєкт",
        "other" to "Інше",
        "draft_status" to "Чернетка",
        "pending_review_status" to "Очікує перевірки",
        "completed_status" to "Завершено",
        "role_admin" to "Адміністратор",
        "role_project_manager" to "Менеджер проєкту",
        "role_inspector" to "Інспектор",
        "general_info_tab" to "Загальна інформація",
        "incidents_hse" to "Інциденти (ОПіЗ)",
        "upload_photo" to "Завантажити фото",
        "findings" to "Зауваження",
        "move_report" to "Перемістити звіт",
        "delete_report" to "Видалити звіт",
        "inspection_findings" to "Зауваження інспекції",
        "no_findings" to "Зауважень ще немає.",
        "add_finding" to "Додати зауваження",
        "edit_finding" to "Редагувати зауваження",
        "category" to "Категорія",
        "description" to "Опис",
        "recommendation" to "Рекомендація",
        "resolved" to "Вирішено",
        "reopen" to "Відкрити знову",
        "resolve" to "Вирішити",
        "select_target_project" to "Оберіть цільовий проєкт",
        "no_other_project" to "Немає іншого проєкту для вибору.",
        "move" to "Перемістити",
        "date" to "Дата",
        "report_project" to "Звіт / проєкт",
        "no_sir_reports_uploaded" to "Звіти ще не завантажено",
        "hse_upload_report_hint" to "Після завантаження SIR тут з’являться спостереження з розділу OBSERVANCES ON HEALTH & SAFETY.",
        "no_hse_observations" to "У завантажених звітах немає даних з ОПіЗ",
        "hse_section_hint" to "Переконайтеся, що вихідний SIR містить розділ OBSERVANCES ON HEALTH & SAFETY.",
        "hse_observations_title" to "Спостереження з SIR: OBSERVANCES ON HEALTH & SAFETY",
        "inspection_date_prefix" to "Інспекція від",
        "answer" to "Відповідь",
        "hse_compliant" to "Відповідає вимогам",
        "hse_issue" to "Виявлено зауваження",
        "review_inspection_report" to "Перевірка інспекційного звіту",
        "revision_reason" to "Причина повернення на доопрацювання",
        "return_for_revision" to "Повернути на доопрацювання",
        "approve" to "Схвалити",
        "no_imported_sir_files" to "Імпортованих файлів SIR не знайдено.",
        "add_inspection_photos" to "Додати фото — перетягніть або виберіть файли",
        "no_photos_selected" to "Фото ще не вибрано.",
        "photos_selected" to "Вибрано фото: {count} з 30. Відкрийте область ще раз, щоб переглянути або видалити їх.",
        "photo_upload_requirements" to "Лише JPEG або PNG, до 10 МБ кожен.",
        "procurement_title" to "Закупівлі",
        "procurement_subtitle" to "Контракти на будівельні роботи за субпроєктами",
        "procurement_load_error" to "Не вдалося завантажити дані закупівель.",
        "proc_number" to "№",
        "proc_batch_number" to "Номер пулу",
        "proc_oblast_name" to "Назва області",
        "proc_oblast_id" to "Ідентифікатор області",
        "proc_subproject_id" to "Ідентифікатор субпроєкту",
        "proc_subproject_lot_id" to "Ідентифікатор лоту субпроєкту",
        "procurement_status" to "Статус закупівлі будробіт",
        "proc_tender_id" to "Ідентифікатор тендеру",
        "proc_prozorro_tender_id" to "Ідентифікатор тендеру на PROZORRO",
        "proc_contractor_name_uk" to "Назва підрядника (укр.)",
        "proc_contractor_name_en" to "Назва підрядника (англ.)",
        "proc_contractor_edrpou" to "Код ЄДРПОУ підрядника",
        "proc_contract_date" to "Дата контракту",
        "proc_contract_end_date" to "Дата завершення контракту",
        "proc_contract_duration" to "Тривалість контракту (робіт), місяці",
        "proc_contract_amount_uah" to "Сума договору на будівництво з ПДВ, грн",
        "proc_contract_amount_eur" to "Сума договору з ПДВ, EUR",
        "proc_financing_difference" to "Різниця між фінансуванням і сумою договору, %",
        "import_export_xlsx" to "Імпорт / експорт XLSX",
        "financial_transfer_title" to "Імпорт або експорт фінансових записів",
        "financial_import_hint" to "Імпорт приймає XLSX-файл, експортований системою для вибраного проєкту.",
        "error_import_financial_records" to "Не вдалося імпортувати фінансові записи: {message}",
        "add_financial_record" to "Додати фінансовий запис",
        "edit_financial_record" to "Редагувати фінансовий запис",
        "reference_number" to "Реєстраційний номер",
        "amount_uah" to "Сума, грн",
        "tranche" to "Транш",
        "city" to "Місто",
        "budget" to "Бюджет",
        "start_date" to "Дата початку",
        "contractor" to "Підрядник",
        "construction_contract" to "Будівельний контракт",
        "acts_of_completed_works" to "Акти виконаних робіт",
        "completed_works_percentage" to "Відсоток виконаних робіт",
        "financial_completion" to "Фінансове виконання",
        "delete_project" to "Видалити проєкт",
        "delete_document_error" to "Не вдалося видалити документ.",
        "source_file" to "Вихідний файл SIR",
        "open_source_file" to "Відкрити вихідний файл SIR",
        "delete_source_file" to "Видалити вихідний файл SIR",
        "delete_source_file_error" to "Не вдалося видалити вихідний документ.",
        "edit_financial_record_tooltip" to "Редагувати фінансовий запис",
        "delete_financial_record_tooltip" to "Видалити фінансовий запис",
        "user_status_active" to "Активний",
        "user_status_pending" to "Очікує",
        "user_status_disabled" to "Вимкнений",
        "severity_low" to "Низька",
        "severity_medium" to "Середня",
        "severity_high" to "Висока",
        "severity_critical" to "Критична",
        "review_report" to "Перевірити звіт",
        "error_delete_report" to "Не вдалося видалити звіт.",
        "error_review_report" to "Не вдалося перевірити звіт: {message}",
        "error_load_findings" to "Не вдалося завантажити зауваження.",
        "error_save_finding" to "Не вдалося зберегти зауваження: {message}",
        "error_update_finding" to "Не вдалося оновити зауваження.",
        "error_delete_finding" to "Не вдалося видалити зауваження.",
        "error_delete_project" to "Не вдалося видалити проєкт.",
        "delete_project_confirmation" to "Видалити проєкт «{name}»? Цю дію неможливо скасувати.",
        "error_delete_act" to "Не вдалося видалити акт.",
        "error_save_act" to "Не вдалося зберегти акт: {message}",
        "error_load_users" to "Не вдалося завантажити користувачів.",
        "error_save_user" to "Не вдалося зберегти користувача: {message}",
        "error_create_user" to "Не вдалося створити користувача: {message}",
        "admin_title" to "Адміністрування",
        "create_user" to "Створити користувача",
        "system_users" to "Користувачі системи",
        "user_full_data" to "Повні дані користувачів",
        "username" to "Логін",
        "full_name" to "Повне ім’я",
        "role" to "Роль",
        "department" to "Відділ",
        "language" to "Мова",
        "last_login" to "Останній вхід",
        "failed_login_attempts" to "Невдалі входи",
        "locked_until" to "Блокування до",
        "created_at" to "Створено",
        "updated_at" to "Оновлено",
        "edit_user" to "Редагувати користувача",
        "delete_user" to "Видалити користувача",
        "delete_user_title" to "Видалити користувача?",
        "delete_user_confirmation" to "Користувача «{username}» буде видалено без можливості відновлення.",
        "error_delete_current_user" to "Не вдалося видалити користувача. Неможливо видалити поточний обліковий запис.",
        "first_name" to "Ім’я",
        "last_name" to "Прізвище",
        "select_role" to "Оберіть роль",
        "new_password_optional" to "Новий пароль (необов’язково)",
        "create" to "Створити",
        "report_title" to "Назва звіту",
        "error_move_report" to "Не вдалося перенести звіт. Перевірте права доступу та обраний проєкт.",
        "error_move_report_detail" to "Не вдалося перенести звіт: {message}",
        "create_project" to "Створити проєкт",
        "selected_projects" to "Вибрано: {count}",
        "clear_selection" to "Скасувати вибір",
        "suspend" to "Призупинити",
        "archive" to "Архівувати",
        "error_suspend_projects" to "Не вдалося призупинити проєкти.",
        "error_archive_projects" to "Не вдалося архівувати проєкти.",
        "select_project_error" to "Оберіть проєкт.",
        "select_subproject_error" to "Оберіть субпроєкт.",
        "select_subproject_part_error" to "Оберіть частину субпроєкту.",
        "latitude" to "Широта",
        "longitude" to "Довгота",
        "latitude_required" to "Широта *",
        "longitude_required" to "Довгота *",
        "upload_xls" to "Завантажити XLS/XLSX",
        "error_upload_photos_after_report" to "Не вдалося завантажити фото: {message}. Можна повторити спробу без створення другого звіту.",
        "error_invalid_iso_date" to "Дата має бути у форматі РРРР-ММ-ДД.",
        "error_report_summary_required" to "Додайте короткий опис звіту перед надсиланням.",
        "error_report_created_photo_upload" to "Звіт створено, але не вдалося завантажити фото: {message}",
        "error_submit_report" to "Не вдалося надіслати звіт: {message}",
        "error_import_inspection_report" to "Не вдалося імпортувати інспекційний звіт: {message}",
        "error_save_draft" to "Не вдалося зберегти чернетку: {message}",
        "add_procurement_record" to "Додати запис",
        "edit_procurement_record" to "Редагувати запис закупівлі",
        "delete_procurement_record" to "Видалити запис закупівлі",
        "delete_procurement_title" to "Видалити запис закупівлі?",
        "delete_procurement_confirmation" to "Запис №{number} буде видалено без можливості відновлення.",
        "error_create_procurement" to "Не вдалося створити запис закупівлі: {message}",
        "error_update_procurement" to "Не вдалося зберегти зміни: {message}",
        "error_delete_procurement" to "Не вдалося видалити запис закупівлі.",
        "project_created_hint" to "Після створення проєкт одразу з’явиться в переліку та на карті.",
        "basic_information" to "Основна інформація",
        "select_parent_project" to "Оберіть батьківський проєкт *",
        "select_parent_subproject" to "Оберіть батьківський субпроєкт *",
        "project_name_required" to "Назва *",
        "project_code_required" to "Код проєкту *",
        "subproject_contract_amount_required" to "Сума контракту субпроєкту, грн *",
        "contract_signed_date" to "Дата укладення контракту",
        "planned_end_date" to "Планова дата завершення",
        "end_date" to "Дата завершення",
        "address_required" to "Адреса *",
        "region_required" to "Область *",
        "city_required" to "Населений пункт *",
        "parameters_and_location" to "Параметри та розташування",
        "financial_parameters" to "Фінанси та строки",
        "sector_required" to "Сектор *",
        "planned_budget_required" to "Плановий бюджет, грн *",
        "engineer_consultant_amount" to "Договір інженера-консультанта, грн",
        "technical_supervision_amount" to "Технічний нагляд, грн",
        "manager_id_required" to "Відповідальний користувач *",
        "error_required_fields" to "Заповніть усі поля, позначені * .",
        "error_positive_budget" to "Бюджет має бути додатним цілим числом.",
        "error_latitude_range" to "Широта має бути в межах від -90 до 90.",
        "error_longitude_range" to "Довгота має бути в межах від -180 до 180.",
        "error_valid_manager" to "Оберіть відповідального користувача.",
        "error_select_parent" to "Оберіть батьківський запис.",
        "error_positive_contract_amount" to "Вкажіть додатну суму контракту.",
        "error_contract_dates_required" to "Заповніть усі дати контракту.",
        "error_create_project" to "Не вдалося створити проєкт: {message}",
        "edit_project" to "Редагувати проєкт",
        "error_load_project" to "Не вдалося завантажити дані проєкту.",
        "project_status_planned" to "Заплановано",
        "project_status_active" to "Активний",
        "project_status_suspended" to "Призупинено",
        "project_status_completed" to "Завершено",
        "project_status_archived" to "Архівовано",
        "project_status_dlp" to "Період відповідальності за дефекти",
        "subproject_data" to "Дані субпроєкту",
        "subproject_part_data" to "Дані частини субпроєкту",
        "contract_duration_hint" to "Тривалість контракту буде розрахована після збереження дат.",
        "design_construction_dates" to "Дати проєктування та будівництва",
        "design_contract_date" to "Договір на проєктування",
        "construction_contract_date" to "Договір на будівництво",
        "construction_start_date" to "Початок будівництва",
        "projected_completion_date" to "Прогнозована дата завершення",
        "currency_iso_required" to "Валюта (ISO) *",
        "error_positive_subproject_contract" to "Вкажіть додатну суму контракту субпроєкту.",
        "error_subproject_dates_required" to "Заповніть усі дати субпроєкту.",
        "error_currency_iso" to "Валюта повинна містити трилітерний ISO-код.",
        "error_save_project" to "Не вдалося зберегти зміни: {message}",
        "save_changes" to "Зберегти зміни",
        "bytes" to "байт",
        "coordinates" to "Координати",
        "days_value" to "{count} днів",
        "contract_duration" to "Тривалість контракту",
        "subproject_contract_amount" to "Сума контракту субпроєкту",
        "engineer_consultant_contract" to "Договір інженера-консультанта",
        "technical_supervision" to "Технічний нагляд",
        "error_engineer_amount" to "Сума договору інженера-консультанта має бути цілим числом.",
        "error_supervision_amount" to "Сума технічного нагляду має бути цілим числом.",
        "login_or_email_required" to "Вкажіть логін або електронну пошту",
        "connection_error" to "Помилка підключення: {message}",
        "login_or_email" to "Логін або електронна пошта",
        "login_or_email_example" to "admin або user@example.com",
        "project_status_planning" to "Планування",
        "act_date" to "Дата акта",
        "currency_short" to "Вал.",
        "author" to "Автор",
        "loading_data" to "Завантаження даних…",
        "loading_dashboard" to "Оновлення головної панелі…",
        "loading_projects" to "Завантаження проєктів…",
        "loading_reports" to "Завантаження інспекційних звітів…",
        "loading_financials" to "Завантаження фінансових даних…",
        "loading_documents" to "Завантаження документів…",
        "loading_photos" to "Завантаження фотографій…",
        "loading_users" to "Завантаження користувачів…",
        "month_january" to "Січень", "month_february" to "Лютий", "month_march" to "Березень", "month_april" to "Квітень",
        "month_may" to "Травень", "month_june" to "Червень", "month_july" to "Липень", "month_august" to "Серпень",
        "month_september" to "Вересень", "month_october" to "Жовтень", "month_november" to "Листопад", "month_december" to "Грудень",
        "manual_sir_entry" to "Заповнити вручну",
        "import_sir_xlsx" to "Імпортувати XLS/XLSX",
        "manual_sir_title" to "Звіт з інспекції майданчика",
        "manual_sir_fund" to "Український фонд соціальних інвестицій (УФСІ)",
        "sir_contractor_section" to "Підрядник",
        "sir_representatives" to "Представники",
        "sir_contractor_representative" to "Представник підрядника",
        "sir_qa_staff" to "Персонал забезпечення якості M4H",
        "sir_usif_representative" to "Представник УФСІ / МОЗ",
        "sir_personnel_weather" to "Персонал на майданчику / погодні умови",
        "sir_skilled_labor" to "Кваліфіковані працівники",
        "sir_unskilled_labor" to "Некваліфіковані працівники",
        "sir_site_management" to "Керівництво на майданчику",
        "sir_weather_conditions" to "Погодні умови",
        "sir_ongoing_activities" to "Поточні роботи",
        "sir_activities_hint" to "Блок / локація | Опис робіт (за позицією BOQ) | За графіком? | Примітки",
        "sir_ongoing_observations" to "Спостереження щодо поточних робіт",
        "sir_one_per_line" to "Одне спостереження в рядку",
        "sir_hse_observations" to "Спостереження з охорони праці та безпеки",
        "sir_hse_hint" to "Спостереження | Так/Ні | Коментар",
        "sir_quality_assessment" to "Оцінка якості",
        "sir_quality_hint" to "Коментар щодо якості | Зауваження щодо усунення (NNC / NTC)",
        "sir_progress_comments" to "Коментарі щодо прогресу",
        "sir_schedule_remarks" to "Зауваження щодо перегляду графіка",
        "sir_inspector_section" to "Персонал забезпечення якості M4H",
        "sir_name" to "Ім’я",
        "sir_title_field" to "Посада",
        "manual_sir_required" to "Заповніть підрядника та інспектора.",
        "unknown_error" to "невідома помилка"
    )

    val en = mapOf(
        "construction_reconstruction" to "Reconstruction",
        "construction_capital_repair" to "Capital repair",
        "construction_new_construction" to "New construction",
        "no_recent_activity" to "No recent activity yet.",
        "activity_project_created" to "Project or subproject created",
        "activity_project_deleted" to "Project or subproject deleted",
        "activity_inspection_imported" to "Inspection report imported",
        "activity_inspection_manual_created" to "Inspection report created manually",
        "activity_financial_created" to "Financial record added",
        "activity_financial_imported" to "Financial records imported",
        "activity_financial_moved" to "Financial record moved",
        "activity_projects_bulk_status_updated" to "Project statuses updated",
        "activity_projects_bulk_reassigned" to "Project managers reassigned",
        "activity_user_created" to "User created",
        "activity_user_updated" to "User details updated",
        "activity_user_status_changed" to "User status changed",
        "activity_user_role_changed" to "User role changed",
        "activity_user_password_reset" to "User password reset",
        "activity_user_deleted" to "User deleted",
        "activity_user_activated" to "Account activated",
        "subproject" to "Subproject",
        "subproject_part" to "Subproject part",
        "choose_date" to "Choose date",
        "password_requirements" to "Password must contain at least 8 characters.",
        "projects_subprojects" to "Projects / subprojects",
        "subprojects" to "Subprojects",
        "no_subprojects" to "No subprojects yet.",
        "projects_by_start_month" to "Projects by work start month",
        "subprojects_count" to "Subprojects: {count}",
        "start_month_axis_label" to "Work start month",
        "monthly_act_payments" to "Monthly payments under acts",
        "monthly_act_payments_hint" to "Act amounts grouped by payment date (or act date).",
        "no_projects_with_start_date" to "No projects have a start date yet.",
        "monthly_project_payments" to "Monthly project payments",
        "no_payments_yet" to "No payments yet.",
        "dashboard" to "Dashboard",
        "projects" to "Projects",
        "map" to "Map",
        "inspection_reports" to "Inspection Reports",
        "login" to "Login",

        "financial_monitoring" to "Financial Monitoring",
        "financial_access_restricted" to "Financial data is restricted. Contact your Project Manager.",
        "access_restricted" to "Access restricted",
        "import_xls" to "Import XLS",
        "export_to_excel" to "Export to Excel",
        "add_record" to "Add Record",
        "monthly_payments" to "Monthly Payments",
        "record_type" to "Record Type",
        "record_type_invoice" to "Invoice",
        "record_type_act" to "Act",
        "record_type_payment" to "Payment",
        "record_type_advance" to "Advance",
        "all_dates" to "All dates",
        "documents" to "Documents",
        "logout" to "Logout",
        "user" to "User",
        "admin" to "Admin",

        "projects_map" to "Projects Map",
        "map_controls" to "Map Controls",
        "map_projects_info" to "The map shows projects available to the current user.",
        "map_marker_info" to "Marker color matches the project status.",
        "markers_count" to "Markers count:",
        "region" to "Oblast",
        "status" to "Status",
        "active" to "Active",
        "planning" to "Planning",
        "completed" to "Completed",

        "projects_title" to "Projects",
        "search_project" to "Search project",
        "filter_label" to "Filter: {name}",
        "filters" to "Filters",
        "geocode_address" to "Calculate from address",
        "geocode_address_loading" to "Calculating coordinates…",
        "geocode_address_required" to "Enter an address, city, or region to calculate coordinates.",
        "geocode_address_not_found" to "Coordinates could not be determined from the address.",
        "geocode_attribution" to "Geodata © OpenStreetMap contributors",
        "map_scope" to "Show on map",
        "map_subprojects" to "Subprojects",
        "map_subproject_parts" to "Subproject parts",
        "expand" to "Expand",
        "collapse" to "Collapse",
        "sector_education" to "Education",
        "sector_healthcare" to "Healthcare",
        "sector_shelter" to "Shelter",
        "search" to "Search",
        "project" to "Project",
        "sort" to "Sort",
        "id" to "ID",
        "name" to "Name",
        "open" to "Open",

        "documents_title" to "Documents",
        "upload_document" to "Upload Document",
        "uploaded_by" to "Uploaded by",
        "type" to "Type",
        "newest_first" to "Newest first",
        "oldest_first" to "Oldest first",
        "no_documents" to "No documents uploaded yet. Click Upload Document to add the first one.",
        "icon" to "Icon",
        "filename" to "Filename",
        "date" to "Date",
        "size" to "Size",
        "actions" to "Actions",

        "contract" to "Contract",
        "design" to "Design",
        "estimate" to "Estimate",
        "financial_doc" to "Financial Doc",
        "photo" to "Photo",

        "welcome_back" to "Welcome back",
        "please_sign_in" to "Please sign in to continue",
        "email" to "Email",
        "password" to "Password",
        "remember_me" to "Remember me",
        "forgot_password" to "Forgot password?",
        "continue_as_guest" to "Continue as guest",
        "guest_access_error" to "Could not start guest access.",
        "password_reset_title" to "Reset password",
        "password_reset_hint" to "Enter your username or email. We will send a link to set a new password.",
        "password_reset_send" to "Send reset link",
        "password_reset_sent" to "If the account exists, a reset link has been sent.",
        "password_reset_failed" to "Could not send the reset link.",
        "sign_in" to "Sign in",
        "toggle_password" to "Toggle password visibility",
        "email_required" to "Email is required",
        "password_required" to "Password is required",
        "invalid_credentials" to "Invalid credentials",

        "login_hero_title" to "Online Monitoring System",
        "login_hero_subtitle" to "A unified system for project tracking, inspections, and financial oversight.",
        "feature_realtime_monitoring" to "Real-time project monitoring",
        "feature_inspection_reports" to "Integrated inspection reports",
        "feature_financial_tools" to "Financial transparency tools",

        "reports_title" to "Inspection Reports",
        "report_id" to "Report ID",
        "report_type" to "Type",
        "inspector" to "Inspector",
        "view" to "View",
        "edit" to "Edit",
        "new_inspection" to "New Inspection",
        "draft" to "Draft",
        "pending_review" to "Pending Review",
        "site_visit" to "Site Visit",
        "safety_check" to "Safety Check",
        "progress_audit" to "Progress Audit",
        "quality_review" to "Quality Review",

        "projects_by_region" to "Projects by Region",
        "reports" to "Reports",
        "issues" to "Issues",
        "recent_activity" to "Recent Activity",
        "project_updated" to "Project updated",
        "inspection_completed" to "Inspection completed",
        "new_report_uploaded" to "New report uploaded",
        "time_2_hours_ago" to "2 hours ago",
        "time_5_hours_ago" to "5 hours ago",
        "time_yesterday" to "Yesterday",
        "reports_by_month" to "Reports by Month",
        "chart_placeholder" to "Chart placeholder",
        "total_budget" to "Total Budget",
        "active_projects" to "Active projects",
        "completed_this_month" to "Completed this month",
        "pending_inspections" to "Pending inspections",
        "in_progress" to "In Progress",
        "delayed" to "Delayed",

        "all" to "All",
        "budget_summary" to "Budget summary",
        "spent_remaining" to "% spent / % remaining",
        "spent" to "Spent",
        "remaining" to "Remaining",

        "invoice_no" to "Invoice #",
        "payment_date" to "Payment Date",
        "amount" to "Amount",
        "currency" to "Currency",
        "currency_eur" to "Euro (EUR)",
        "currency_uah" to "Hryvnia (UAH)",
        "milestone" to "Milestone",
        "planned" to "Planned",
        "unplanned" to "Unplanned",
        "final" to "Final",

        "edit_inspection" to "Edit Inspection",
        "create_inspection" to "Create Inspection",
        "rejected" to "Rejected",
        "cannot_be_future_date" to "Cannot be a future date",
        "gps_coordinates" to "GPS coordinates",
        "optional_on_web_accuracy_warning" to "Optional on web. Accuracy warning if > 50m.",
        "comments" to "Comments",
        "photos" to "Photos",
        "drag_and_drop_zone" to "Drag-and-drop zone / camera upload",
        "no_photos_uploaded_yet" to "No photos uploaded yet.",
        "photo_thumbnails_go_here" to "Photo thumbnails go here",
        "save_draft" to "Save Draft",
        "submit_report" to "Submit Report",
        "inspector_label" to "Inspector",
        "date_label" to "Date",

        "address" to "Address",
        "sector" to "Sector",
        "construction_type" to "Construction type",
        "budget_planned" to "Budget Planned",
        "amount_spent" to "Amount Spent",
        "budget_remaining" to "Budget Remaining",
        "general_info" to "General Info",
        "inspection_reports_tab" to "Inspection Reports",
        "financials" to "Financials",
        "documents_tab" to "Documents",
        "incidents" to "Incidents",
        "coming_next" to "Coming next",
        "project_documents" to "Project documents",
        "sir_source_files" to "SIR source files",
        "select_project" to "Select project",
        "select_subproject" to "Select subproject",
        "select_subproject_part" to "Select subproject part",
        "choose_file" to "Choose file",
        "cancel" to "Cancel",
        "save" to "Save",
        "close" to "Close",
        "delete" to "Delete",
        "open_document" to "Open document",
        "no_project_documents" to "No project documents found.",
        "no_reports" to "No inspection reports found.",
        "inspection_report" to "Inspection report",
        "financial_records" to "Financial records",
        "completed_works_by_acts" to "Sum of completed works by acts",
        "only_completed_works" to "Only completed works confirmed by acts are included.",
        "no_acts" to "No acts found.",
        "act_documents" to "Act documents",
        "file_name" to "File name",
        "subproject" to "Subproject",
        "other" to "Other",
        "draft_status" to "Draft",
        "pending_review_status" to "Pending review",
        "completed_status" to "Completed",
        "role_admin" to "Administrator",
        "role_project_manager" to "Project Manager",
        "role_inspector" to "Inspector",
        "general_info_tab" to "General Info",
        "incidents_hse" to "Incidents (HSE)",
        "upload_photo" to "Upload photo",
        "findings" to "Findings",
        "move_report" to "Move report",
        "delete_report" to "Delete report",
        "inspection_findings" to "Inspection findings",
        "no_findings" to "No findings yet.",
        "add_finding" to "Add finding",
        "edit_finding" to "Edit finding",
        "category" to "Category",
        "description" to "Description",
        "recommendation" to "Recommendation",
        "resolved" to "Resolved",
        "reopen" to "Reopen",
        "resolve" to "Resolve",
        "select_target_project" to "Select target project",
        "no_other_project" to "There is no other project to select.",
        "move" to "Move",
        "report_project" to "Report / project",
        "no_sir_reports_uploaded" to "No inspection reports have been uploaded yet",
        "hse_upload_report_hint" to "Observations from the OBSERVANCES ON HEALTH & SAFETY section will appear here after a SIR is uploaded.",
        "no_hse_observations" to "No HSE observations were found in the uploaded reports",
        "hse_section_hint" to "Make sure the original SIR contains an OBSERVANCES ON HEALTH & SAFETY section.",
        "hse_observations_title" to "SIR observations: OBSERVANCES ON HEALTH & SAFETY",
        "inspection_date_prefix" to "Inspection on",
        "answer" to "Answer",
        "hse_compliant" to "Compliant",
        "hse_issue" to "Issue found",
        "review_inspection_report" to "Review inspection report",
        "revision_reason" to "Reason for returning for revision",
        "return_for_revision" to "Return for revision",
        "approve" to "Approve",
        "no_imported_sir_files" to "No imported SIR files found.",
        "add_inspection_photos" to "Add photos — drag and drop or select files",
        "no_photos_selected" to "No photos selected yet.",
        "photos_selected" to "{count} of 30 photos selected. Open the area again to preview or remove them.",
        "photo_upload_requirements" to "JPEG or PNG only, up to 10 MB each.",
        "procurement_title" to "Procurement",
        "procurement_subtitle" to "Construction works contracts by subproject",
        "procurement_load_error" to "Could not load procurement data.",
        "proc_number" to "No.",
        "proc_batch_number" to "Pool number",
        "proc_oblast_name" to "Oblast name",
        "proc_oblast_id" to "Oblast identifier",
        "proc_subproject_id" to "Subproject identifier",
        "proc_subproject_lot_id" to "Subproject lot identifier",
        "procurement_status" to "Construction procurement status",
        "proc_tender_id" to "Tender identifier",
        "proc_prozorro_tender_id" to "PROZORRO tender identifier",
        "proc_contractor_name_uk" to "Contractor name (Ukrainian)",
        "proc_contractor_name_en" to "Contractor name (English)",
        "proc_contractor_edrpou" to "Contractor EDRPOU code",
        "proc_contract_date" to "Contract date",
        "proc_contract_end_date" to "Contract end date",
        "proc_contract_duration" to "Contract works duration, months",
        "proc_contract_amount_uah" to "Construction contract amount incl. VAT, UAH",
        "proc_contract_amount_eur" to "Contract amount incl. VAT, EUR",
        "proc_financing_difference" to "Difference between financing and contract amount, %",
        "import_export_xlsx" to "Import / export XLSX",
        "financial_transfer_title" to "Import or export financial records",
        "financial_import_hint" to "Import accepts an XLSX file exported by the system for the selected project.",
        "error_import_financial_records" to "Could not import financial records: {message}",
        "add_financial_record" to "Add financial record",
        "edit_financial_record" to "Edit financial record",
        "reference_number" to "Reference number",
        "amount_uah" to "Amount, UAH",
        "tranche" to "Tranche",
        "city" to "City",
        "budget" to "Budget",
        "start_date" to "Start date",
        "contractor" to "Contractor",
        "construction_contract" to "Construction contract",
        "acts_of_completed_works" to "Acts of completed works",
        "completed_works_percentage" to "Completed works percentage",
        "financial_completion" to "Financial completion",
        "delete_project" to "Delete project",
        "delete_document_error" to "Could not delete document.",
        "source_file" to "SIR source file",
        "open_source_file" to "Open SIR source file",
        "delete_source_file" to "Delete SIR source file",
        "delete_source_file_error" to "Could not delete source document.",
        "edit_financial_record_tooltip" to "Edit financial record",
        "delete_financial_record_tooltip" to "Delete financial record",
        "user_status_active" to "Active",
        "user_status_pending" to "Pending",
        "user_status_disabled" to "Disabled",
        "severity_low" to "Low",
        "severity_medium" to "Medium",
        "severity_high" to "High",
        "severity_critical" to "Critical",
        "review_report" to "Review report",
        "error_delete_report" to "Could not delete report.",
        "error_review_report" to "Could not review report: {message}",
        "error_load_findings" to "Could not load findings.",
        "error_save_finding" to "Could not save finding: {message}",
        "error_update_finding" to "Could not update finding.",
        "error_delete_finding" to "Could not delete finding.",
        "error_delete_project" to "Could not delete project.",
        "delete_project_confirmation" to "Delete project “{name}”? This action cannot be undone.",
        "error_delete_act" to "Could not delete act.",
        "error_save_act" to "Could not save act: {message}",
        "error_load_users" to "Could not load users.",
        "error_save_user" to "Could not save user: {message}",
        "error_create_user" to "Could not create user: {message}",
        "admin_title" to "Administration",
        "create_user" to "Create user",
        "system_users" to "System users",
        "user_full_data" to "Complete user data",
        "username" to "Username",
        "full_name" to "Full name",
        "role" to "Role",
        "department" to "Department",
        "language" to "Lang",
        "last_login" to "Last login",
        "failed_login_attempts" to "Failed logins",
        "locked_until" to "Locked until",
        "created_at" to "Created",
        "updated_at" to "Updated",
        "edit_user" to "Edit user",
        "delete_user" to "Delete user",
        "delete_user_title" to "Delete user?",
        "delete_user_confirmation" to "User “{username}” will be permanently deleted.",
        "error_delete_current_user" to "Could not delete the current user account.",
        "first_name" to "First name",
        "last_name" to "Last name",
        "select_role" to "Select role",
        "new_password_optional" to "New password (optional)",
        "create" to "Create",
        "report_title" to "Report title",
        "error_move_report" to "Could not move report. Check access rights and the selected project.",
        "error_move_report_detail" to "Could not move report: {message}",
        "create_project" to "Create project",
        "selected_projects" to "Selected: {count}",
        "clear_selection" to "Clear selection",
        "suspend" to "Suspend",
        "archive" to "Archive",
        "error_suspend_projects" to "Could not suspend projects.",
        "error_archive_projects" to "Could not archive projects.",
        "select_project_error" to "Select a project.",
        "select_subproject_error" to "Select a subproject.",
        "select_subproject_part_error" to "Select a subproject part.",
        "latitude" to "Latitude",
        "longitude" to "Longitude",
        "latitude_required" to "Latitude *",
        "longitude_required" to "Longitude *",
        "upload_xls" to "Upload XLS/XLSX",
        "error_upload_photos_after_report" to "Could not upload photos: {message}. You can retry without creating another report.",
        "error_invalid_iso_date" to "Date must be in YYYY-MM-DD format.",
        "error_report_summary_required" to "Add a short report description before submitting.",
        "error_report_created_photo_upload" to "Report was created, but photos could not be uploaded: {message}",
        "error_submit_report" to "Could not submit report: {message}",
        "error_import_inspection_report" to "Could not import inspection report: {message}",
        "error_save_draft" to "Could not save draft: {message}",
        "add_procurement_record" to "Add record",
        "edit_procurement_record" to "Edit procurement record",
        "delete_procurement_record" to "Delete procurement record",
        "delete_procurement_title" to "Delete procurement record?",
        "delete_procurement_confirmation" to "Record #{number} will be permanently deleted.",
        "error_create_procurement" to "Could not create procurement record: {message}",
        "error_update_procurement" to "Could not save changes: {message}",
        "error_delete_procurement" to "Could not delete procurement record.",
        "project_created_hint" to "The project will appear in the list and on the map immediately after it is created.",
        "basic_information" to "Basic information",
        "select_parent_project" to "Select parent project *",
        "select_parent_subproject" to "Select parent subproject *",
        "project_name_required" to "Name *",
        "project_code_required" to "Project code *",
        "subproject_contract_amount_required" to "Subproject contract amount, UAH *",
        "contract_signed_date" to "Contract signing date",
        "planned_end_date" to "Planned completion date",
        "end_date" to "End date",
        "address_required" to "Address *",
        "region_required" to "Oblast *",
        "city_required" to "Settlement *",
        "parameters_and_location" to "Parameters and location",
        "financial_parameters" to "Financials and timeline",
        "sector_required" to "Sector *",
        "planned_budget_required" to "Planned budget, UAH *",
        "engineer_consultant_amount" to "Engineer-consultant contract, UAH",
        "technical_supervision_amount" to "Technical supervision, UAH",
        "manager_id_required" to "Responsible user *",
        "error_required_fields" to "Fill in all fields marked with *.",
        "error_positive_budget" to "Budget must be a positive whole number.",
        "error_latitude_range" to "Latitude must be between -90 and 90.",
        "error_longitude_range" to "Longitude must be between -180 and 180.",
        "error_valid_manager" to "Select a responsible user.",
        "error_select_parent" to "Select a parent record.",
        "error_positive_contract_amount" to "Enter a positive contract amount.",
        "error_contract_dates_required" to "Fill in all contract dates.",
        "error_create_project" to "Could not create project: {message}",
        "edit_project" to "Edit project",
        "error_load_project" to "Could not load project data.",
        "project_status_planned" to "Planned",
        "project_status_active" to "Active",
        "project_status_suspended" to "Suspended",
        "project_status_completed" to "Completed",
        "project_status_archived" to "Archived",
        "project_status_dlp" to "Defect liability period",
        "subproject_data" to "Subproject data",
        "subproject_part_data" to "Subproject part data",
        "contract_duration_hint" to "Contract duration will be calculated after dates are saved.",
        "design_construction_dates" to "Design and construction dates",
        "design_contract_date" to "Design contract date",
        "construction_contract_date" to "Construction contract date",
        "construction_start_date" to "Construction start date",
        "projected_completion_date" to "Projected completion date",
        "currency_iso_required" to "Currency (ISO) *",
        "error_positive_subproject_contract" to "Enter a positive subproject contract amount.",
        "error_subproject_dates_required" to "Fill in all subproject dates.",
        "error_currency_iso" to "Currency must be a three-letter ISO code.",
        "error_save_project" to "Could not save changes: {message}",
        "save_changes" to "Save changes",
        "bytes" to "bytes",
        "coordinates" to "Coordinates",
        "days_value" to "{count} days",
        "contract_duration" to "Contract duration",
        "subproject_contract_amount" to "Subproject contract amount",
        "engineer_consultant_contract" to "Engineer-consultant contract",
        "technical_supervision" to "Technical supervision",
        "error_engineer_amount" to "Engineer-consultant contract amount must be a whole number.",
        "error_supervision_amount" to "Technical supervision amount must be a whole number.",
        "login_or_email_required" to "Enter a username or email address",
        "connection_error" to "Connection error: {message}",
        "login_or_email" to "Username or email address",
        "login_or_email_example" to "admin or user@example.com",
        "project_status_planning" to "Planning",
        "act_date" to "Act date",
        "currency_short" to "Curr.",
        "author" to "Author",
        "loading_data" to "Loading data…",
        "loading_dashboard" to "Updating dashboard…",
        "loading_projects" to "Loading projects…",
        "loading_reports" to "Loading inspection reports…",
        "loading_financials" to "Loading financial data…",
        "loading_documents" to "Loading documents…",
        "loading_photos" to "Loading photos…",
        "loading_users" to "Loading users…",
        "month_january" to "January", "month_february" to "February", "month_march" to "March", "month_april" to "April",
        "month_may" to "May", "month_june" to "June", "month_july" to "July", "month_august" to "August",
        "month_september" to "September", "month_october" to "October", "month_november" to "November", "month_december" to "December",
        "manual_sir_entry" to "Fill in manually",
        "import_sir_xlsx" to "Import XLS/XLSX",
        "manual_sir_title" to "Site Inspection Report",
        "manual_sir_fund" to "Ukrainian Social Investment Fund (USIF)",
        "sir_contractor_section" to "Contractor",
        "sir_representatives" to "Representatives",
        "sir_contractor_representative" to "Contractor's representative",
        "sir_qa_staff" to "M4H QA staff",
        "sir_usif_representative" to "USIF / MOH representative",
        "sir_personnel_weather" to "Personnel on site / weather conditions",
        "sir_skilled_labor" to "Skilled labor",
        "sir_unskilled_labor" to "Unskilled labor",
        "sir_site_management" to "Management on site",
        "sir_weather_conditions" to "Weather conditions",
        "sir_ongoing_activities" to "Ongoing activities",
        "sir_activities_hint" to "Block / location | Description of work (per BOQ item) | Per schedule? | Remarks",
        "sir_ongoing_observations" to "Observances on ongoing activities",
        "sir_one_per_line" to "One observation per line",
        "sir_hse_observations" to "Observances on health & safety",
        "sir_hse_hint" to "Observation | Yes/No | Comment",
        "sir_quality_assessment" to "Narrative assessment — comments on quality",
        "sir_quality_hint" to "Comment on quality | Rectification remarks (NNC / NTC)",
        "sir_progress_comments" to "Comments on progress",
        "sir_schedule_remarks" to "Schedule revision remarks",
        "sir_inspector_section" to "M4H QA staff",
        "sir_name" to "Name",
        "sir_title_field" to "Title",
        "manual_sir_required" to "Fill in the contractor and inspector.",
        "unknown_error" to "unknown error"
    )
}
