package oms.umitaf.domain

import java.time.LocalDate

data class ProcurementRecord(
    val id: Long,
    val batchId: Int,
    val oblastName: String,
    val oblastId: String,
    val subProjectId: String,
    val subProjectLotId: String?,
    val purchaseStatus: String?,
    val tenderId: String?,
    val prozorroTenderId: String?,
    val contractorNameUkr: String?,
    val contractorNameEng: String?,
    val contractorId: String?,
    val contractDate: LocalDate?,
    val contractEndDate: LocalDate?,
    val contractDurationMonths: Int?,
    val contractAmountUah: Double?,
    val contractAmountEur: Double?,
    val financingContractDifferencePct: Double?,
    val promotorName: String? = null,
    val subprojectNameUk: String? = null,
    val subprojectNameEn: String? = null,
    val sourceContractType: String? = null,
    val subprojectTotalCostUah: Double? = null,
    val subprojectEibFinancingUah: Double? = null,
    val subprojectLocalFinancingUah: Double? = null,
    val estimatedTotalEur: Double? = null,
    val estimatedTotalUah: Double? = null,
    val estimatedEibEur: Double? = null,
    val estimatedEibUah: Double? = null,
    val estimatedLocalEur: Double? = null,
    val estimatedLocalUah: Double? = null,
    val procurementMethod: String? = null,
    val tenderDocumentType: String? = null,
    val publishedInOjeu: String? = null,
    val estimatedProzorroDate: LocalDate? = null,
    val estimatedBidSubmissionDate: LocalDate? = null,
    val estimatedContractDate: LocalDate? = null,
    val estimatedContractEndDate: LocalDate? = null,
    val localFinancingPct: Double? = null,
    val comments: String? = null,
    val sourceStatusCode: String? = null,
    val projectId: Long? = null
)
