services:

  mysql:

    image: mysql:8.4

    container_name: usif-mysql

    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:

      # Пароль суперпользователя MySQL.
      MYSQL_ROOT_PASSWORD: root

      # База даних, яка буде створена автоматично.
      MYSQL_DATABASE: usif

      # Робочий користувач застосунку.
      MYSQL_USER: usif_user

      # Пароль робочого користувача.
      MYSQL_PASSWORD: usif_password

    volumes:

      # Дані БД зберігатимуться між перезапусками контейнера.
      - mysql-data:/var/lib/mysql


volumes:

  mysql-data: