CREATE TABLE procurement_records (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    record_number INT NOT NULL,
    batch_id INT NOT NULL,
    oblast_name VARCHAR(255) NOT NULL,
    oblast_id VARCHAR(32) NOT NULL,
    sub_project_id VARCHAR(64) NOT NULL,
    sub_project_lot_id VARCHAR(64) NOT NULL,
    purchase_status VARCHAR(255) NOT NULL,
    tender_id VARCHAR(128) NULL,
    prozorro_tender_id VARCHAR(512) NULL,
    contractor_name_ukr VARCHAR(500) NULL,
    contractor_name_eng VARCHAR(500) NULL,
    contractor_id VARCHAR(32) NULL,
    contract_date DATE NULL,
    contract_end_date DATE NULL,
    contract_duration_months INT NULL,
    contract_amount_uah DECIMAL(18,2) NULL,
    contract_amount_eur DECIMAL(18,4) NULL,
    financing_contract_difference_pct DECIMAL(14,10) NULL,
    INDEX idx_procurement_batch (batch_id),
    INDEX idx_procurement_oblast (oblast_id),
    INDEX idx_procurement_subproject (sub_project_id)
);
