ktor:

  deployment:

    # HTTP-порт серверного застосунку.
    port: 8080

    # Дозволяє автоматично перезапускати сервер
    # після зміни коду під час розробки.
    watch:
      - classes

  application:

    # Список модулів, які Ktor повинен викликати
    # після запуску HTTP-сервера.
    modules:
      - oms.ufsi.ApplicationKt.module