package oms.ufsi.domain

import java.time.LocalDate

/** Fields of a project that may be changed without changing its lifecycle status. */
data class ProjectPatch(
    val name: String,
    val siteName: String,
    val siteNumber: String,
    val description: String?,
    val address: String?,
    val region: String?,
    val city: String?,
    val status: ProjectStatus,
    val latitude: Double?,
    val longitude: Double?,
    val sector: String?,
    val constructionType: String?,
    val trancheNumber: Int,
    val budgetPlanned: Long,
    val engineerConsultantContractAmount: Long?,
    val technicalSupervisionAmount: Long?,
    val subprojectContractAmount: Long?,
    val startDate: LocalDate?,
    val endDate: LocalDate?,
    val contractSignedDate: LocalDate?,
    val plannedEndDate: LocalDate?,
    val designContractSigningDate: LocalDate?,
    val designStartDate: LocalDate? = null,
    val designPlannedEndDate: LocalDate? = null,
    val constructionContractSigningDate: LocalDate?,
    val constructionStartDate: LocalDate?,
    val projectedCompletionTime: LocalDate?,
    val currency: String,
    val contractorName: String?,
    val designerName: String? = null,
    val designContractNumber: String? = null,
    val designContractTerm: String? = null,
    val constructionContractNumber: String? = null,
    val amounts: Map<String, ProjectAmount> = emptyMap(),
    val technicalSupervisionName: String? = null,
    val technicalSupervisionContractNumber: String? = null,
    val technicalSupervisionContractDate: LocalDate? = null,
    val technicalSupervisionStartDate: LocalDate? = null,
    val technicalSupervisionPlannedEndDate: LocalDate? = null,
    val engineerConsultantName: String? = null,
    val engineerConsultantContractNumber: String? = null,
    val engineerConsultantContractDate: LocalDate? = null,
    val engineerConsultantStartDate: LocalDate? = null,
    val engineerConsultantPlannedEndDate: LocalDate? = null
)
