GET http://localhost:8080/api/v1/roles

###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "inspector1",
  "email": "inspector1@usif.local",
  "password": "12345",
  "roleCode": "INSPECTOR"
}